"""create staff management table

Revision ID: 1087de5f129d
Revises: fc7658cea0ff
Create Date: 2026-07-08 15:45:05.828450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1087de5f129d'
down_revision: Union[str, Sequence[str], None] = 'fc7658cea0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('staff_name', sa.String(length=225), nullable=False),
    sa.Column('staff_age', sa.Integer(), nullable=True),
    sa.Column('staff_email', sa.String(length=225), nullable=False),
    sa.Column('staff_phone', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_staff_phone'), 'staff', ['staff_phone'], unique=False)
    op.create_table('rel_permission_staff',
    sa.Column('rel_staff_role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_staff_role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_permission_staff')
    op.drop_index(op.f('ix_staff_staff_phone'), table_name='staff')
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
