"""increase interest rate precision

Revision ID: 167b0ce3e22f
Revises: 9ad93cee7756
Create Date: 2026-06-22 15:50:20.803375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167b0ce3e22f'
down_revision: Union[str, Sequence[str], None] = '9ad93cee7756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loan_offer', 'interest_rate',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loan_offer', 'interest_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
