"""fix relationship with customer and relloanoffer

Revision ID: 6fab84262b79
Revises: b03f7cda9cff
Create Date: 2026-05-23 21:20:07.709028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fab84262b79'
down_revision: Union[str, Sequence[str], None] = 'b03f7cda9cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
