"""remove unique constraints

Revision ID: 9ad93cee7756
Revises: d1fc1e3da17c
Create Date: 2026-05-24 12:34:35.269426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad93cee7756'
down_revision: Union[str, Sequence[str], None] = 'd1fc1e3da17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    # ### end Alembic commands ###
