"""add tables migration

Revision ID: b03f7cda9cff
Revises: 1fcb28c34fea
Create Date: 2026-05-23 20:52:07.050543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03f7cda9cff'
down_revision: Union[str, Sequence[str], None] = '1fcb28c34fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_score',
    sa.Column('credit_score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('credit_score_id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('current_loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pre_approved_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_age'), 'customer', ['age'], unique=False)
    op.create_index(op.f('ix_customer_city'), 'customer', ['city'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_table('loan_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('conversation_history', sa.String(length=1024), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('monthly_emi', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('loan_offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('amount_range_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_range_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('salary_slip',
    sa.Column('slip_id', sa.String(length=255), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('slip_id')
    )
    op.create_table('rel_credit_score_customer',
    sa.Column('rel_credit_score_customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_score_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['credit_score_id'], ['credit_score.credit_score_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_credit_score_customer_id')
    )
    op.create_table('rel_loan_application_customer',
    sa.Column('rel_loan_application_customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_loan_application_customer_id')
    )
    op.create_table('rel_loan_offer_customer',
    sa.Column('rel_offer_customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['loan_offer.offer_id'], ),
    sa.PrimaryKeyConstraint('rel_offer_customer_id')
    )
    op.create_table('rel_salary_slip_customer',
    sa.Column('rel_salary_slip_customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('slip_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['salary_slip.slip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_salary_slip_customer_id')
    )
    op.create_table('rel_salary_slip_loan_application',
    sa.Column('rel_salary_slip_loan_application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('slip_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['salary_slip.slip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_salary_slip_loan_application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_salary_slip_loan_application')
    op.drop_table('rel_salary_slip_customer')
    op.drop_table('rel_loan_offer_customer')
    op.drop_table('rel_loan_application_customer')
    op.drop_table('rel_credit_score_customer')
    op.drop_table('salary_slip')
    op.drop_table('loan_offer')
    op.drop_table('loan_application')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_city'), table_name='customer')
    op.drop_index(op.f('ix_customer_age'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('credit_score')
    # ### end Alembic commands ###
