"""add is_deleted column in staff table

Revision ID: c7a247f04877
Revises: 1087de5f129d
Create Date: 2026-07-08 16:02:16.509265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a247f04877'
down_revision: Union[str, Sequence[str], None] = '1087de5f129d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'is_deleted')
    # ### end Alembic commands ###
