"""fix relationship mapping in salaryslip and loan application 

Revision ID: d1fc1e3da17c
Revises: f40cf000367b
Create Date: 2026-05-23 21:33:01.659516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fc1e3da17c'
down_revision: Union[str, Sequence[str], None] = 'f40cf000367b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
