"""fix relationship with customer and relloanoffercustomer 

Revision ID: f40cf000367b
Revises: 6fab84262b79
Create Date: 2026-05-23 21:24:32.190747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40cf000367b'
down_revision: Union[str, Sequence[str], None] = '6fab84262b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
