"""initial migration

Revision ID: 581613a7abea
Revises: 
Create Date: 2026-05-15 16:04:44.968065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581613a7abea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_offer')
    op.drop_table('rel_loan_application_customer')
    op.drop_table('rel_credit_score_customer')
    op.drop_table('rel_salary_slip_customer')
    op.drop_table('salary_slip')
    op.drop_table('rel_loan_offer_customer')
    op.drop_table('rel_salary_slip_loan_application')
    op.drop_index(op.f('ix_customer_age'), table_name='customer')
    op.drop_index(op.f('ix_customer_city'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('loan_application')
    op.drop_table('credit_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_score',
    sa.Column('credit_score_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('credit_score_id', name=op.f('credit_score_pkey'))
    )
    op.create_table('loan_application',
    sa.Column('application_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('conversation_history', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('tenure_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('monthly_emi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('application_id', name=op.f('loan_application_pkey'))
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('current_loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('pre_approved_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customer_pkey'))
    )
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_city'), 'customer', ['city'], unique=False)
    op.create_index(op.f('ix_customer_age'), 'customer', ['age'], unique=False)
    op.create_table('rel_salary_slip_loan_application',
    sa.Column('rel_salary_slip_loan_application_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], name=op.f('rel_salary_slip_loan_application_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['salary_slip.slip_id'], name=op.f('rel_salary_slip_loan_application_slip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_salary_slip_loan_application_id', name=op.f('rel_salary_slip_loan_application_pkey'))
    )
    op.create_table('rel_loan_offer_customer',
    sa.Column('rel_offer_customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('rel_loan_offer_customer_customer_id_fkey')),
    sa.ForeignKeyConstraint(['offer_id'], ['loan_offer.offer_id'], name=op.f('rel_loan_offer_customer_offer_id_fkey')),
    sa.PrimaryKeyConstraint('rel_offer_customer_id', name=op.f('rel_loan_offer_customer_pkey'))
    )
    op.create_table('salary_slip',
    sa.Column('slip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monthly_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('slip_id', name=op.f('salary_slip_pkey'))
    )
    op.create_table('rel_salary_slip_customer',
    sa.Column('rel_salary_slip_customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('slip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('rel_salary_slip_customer_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['salary_slip.slip_id'], name=op.f('rel_salary_slip_customer_slip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_salary_slip_customer_id', name=op.f('rel_salary_slip_customer_pkey'))
    )
    op.create_table('rel_credit_score_customer',
    sa.Column('rel_credit_score_customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credit_score_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_score_id'], ['credit_score.credit_score_id'], name=op.f('rel_credit_score_customer_credit_score_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('rel_credit_score_customer_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_credit_score_customer_id', name=op.f('rel_credit_score_customer_pkey'))
    )
    op.create_table('rel_loan_application_customer',
    sa.Column('rel_loan_application_customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], name=op.f('rel_loan_application_customer_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('rel_loan_application_customer_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_loan_application_customer_id', name=op.f('rel_loan_application_customer_pkey'))
    )
    op.create_table('loan_offer',
    sa.Column('offer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount_range_min', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount_range_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('tenure_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('offer_id', name=op.f('loan_offer_pkey'))
    )
    # ### end Alembic commands ###
